export const content = {
    search: "جستجو",
    home: "صفحه اصلی",
    shop: "فروشگاه",
    about: "درباره ما",
    contact: "تماس با ما",
    blog: "وبلاگ",
    profile: "حساب کاربری",
    logout: "خروج",
    cart: "سبد خرید",
    addToCart: "افزودن به سبد خرید",
    currencyUnit: "تومان",
    login: "ورود",
    signup: "ثبت نام",
    category: "دسته بندی",
    qty: "تعداد",
    price: "قیمت",
    unitPrice: "قیمت واحد",
    totalPrice: "قیمت کل",
    totalPayable: "مبلغ قابل پرداخت",
    totalSum: "جمع کل",
    cancel: "لغو",
    submit: "ثبت",
    confirm: "تایید",
    and: "و",
    delete: "حذف",
    deleteItem: "حذف از سبد",
    deleteCartItemParagraph: "از سبد خرید شما حذف شود؟",
    orderSummary: "خلاصه سفارش",
    deliveryFee: "هزینه ارسال",
    submitOrder: "ثبت سفارش",
    pay: "پرداخت"
}