export const content = {
    search: "جستجو",
    home: "صفحه اصلی",
    shop: "فروشگاه",
    about: "درباره ما",
    contact: "ارتباط با ما",
    blog: "وبلاگ",
    profile: "حساب کاربری",
    logout: "خروج",
    cart: "سبد خرید",
    addToCart: "افزودن به سبد خرید",
    currencyUnit: "تومان",
    login: "ورود",
    signup: "ثبت نام",
    category: "دسته بندی",
    categories: "دسته بندی ها",
    qty: "تعداد",
    price: "قیمت",
    priceRange: "محدوده قیمت",
    unitPrice: "قیمت واحد",
    totalPrice: "قیمت کل",
    totalPayable: "مبلغ قابل پرداخت",
    totalSum: "جمع کل",
    cancel: "لغو",
    submit: "ثبت",
    confirm: "تایید",
    and: "و",
    delete: "حذف",
    deleteItem: "حذف از سبد",
    phoneNumber: "شماره تلفن",
    requiredPhoneNumber: "لطفا شماره تلفن خود را وارد کنید",
    invalidPhoneNumber: "لطفا شماره تلفن را به درستی وارد نمایید",
    didntGetTheCode: "کدی دریافت نکرده اید ؟",
    pleaseEnterOTPSentTo: "لطفا کد یکبار مصرف ارسال شده را وارد کنید",
    dontHaveAnAccount: "هنوز حسابی ندارید؟",
    signInWithGoogle: "ورود با حساب گوگل",
    resend: "ارسال دوباره",
    back: "بازگشت",
    createAccount: "ساخت حساب کاربری",
    alreadyHaveAnAccount: "حساب کاربری دارید؟",
    fullName: "نام و نام خانوادگی",
    signUpWithGoogle: "ساخت حساب از طریق گوگل",
    signIn: "وارد شوید",
    deleteCartItemParagraph: "از سبد خرید شما حذف شود؟",
    orderSummary: "خلاصه سفارش",
    deliveryFee: "هزینه ارسال",
    submitOrder: "ثبت سفارش",
    pay: "پرداخت",
    gotoCart: "برو به سبد خرید",
    viewCart: "مشاهده سبد خرید",
    count: "عدد",
    newest: "جدید ترین",
    oldest: "قدیمی ترین",
    cheapest: "ارزان ترین",
    mostExpensive: "گران ترین",
    bestSeller: "پرفروش ترین",
    filter: "فیلتر  ",
    emptyCart: "سبد خرید خالی است",
    shopNow: "خرید کن ببه"
}