export const content = {
    search: "جستجو",
    home: "صفحه اصلی",
    shop: "فروشگاه",
    about: "درباره ما",
    contact: "ارتباط با ما",
    contactUS: "با ما در ارتباط باشید",
    contactWays: "راه‌های ارتباطی",
    blog: "وبلاگ",
    profile: "حساب کاربری",
    logout: "خروج",
    cart: "سبد خرید",
    addToCart: "افزودن به سبد خرید",
    currencyUnit: "تومان",
    productTitle: "نام کالا",
    login: "ورود",
    signup: "ثبت نام",
    faqs: "سوالات متداول",
    category: "دسته بندی",
    categories: "دسته بندی ها",
    nodata: "نتیجه‌ای یافت نشد.",
    selectShippingMethod: "انتخاب نحوه ارسال",
    shippingMethod: "نحوه ارسال",
    chooseAddress: "انتخاب آدرس",
    recieverFullName: "نام تحویل‌گیرنده",
    addNewAddress: "ثبت آدرس جدید",
    noAddress: "هنوز آدرسی ثبت نکرده‌اید.",
    postalCode: "کد پستی",
    address: "آدرس",
    province: "استان",
    qty: "تعداد",
    price: "قیمت",
    priceRange: "محدوده قیمت",
    checkout: "نهایی سازی سفارش",
    myOrders: "سفارش‌های من",
    myAddresses: "آدرس‌های من",
    loginToSubmitOrder: "برای ثبت سفارش ابتدا وارد شوید.",
    stock: "موجودی",
    availableProductsOnly: "فقط کالاهای موجود",
    unitPrice: "قیمت واحد",
    totalPrice: "قیمت کل",
    totalPayable: "مبلغ قابل پرداخت",
    totalSum: "جمع کل",
    cancel: "لغو",
    submit: "ثبت",
    confirm: "تایید",
    and: "و",
    edit: "ویرایش",
    delete: "حذف",
    deleteItem: "حذف از سبد",
    phoneNumber: "شماره تلفن",
    addressTitle: "عنوان آدرس",
    requiredPhoneNumber: "لطفا شماره تلفن خود را وارد کنید",
    invalidPhoneNumber: "لطفا شماره تلفن را به درستی وارد نمایید",
    didntGetTheCode: "کدی دریافت نکرده اید ؟",
    pleaseEnterOTPSentTo: "لطفا کد یکبار مصرف ارسال شده را وارد کنید",
    dontHaveAnAccount: "هنوز حسابی ندارید؟",
    signInWithGoogle: "ورود با حساب گوگل",
    resend: "ارسال دوباره",
    back: "بازگشت",
    createAccount: "ساخت حساب کاربری",
    alreadyHaveAnAccount: "حساب کاربری دارید؟",
    fullName: "نام و نام خانوادگی",
    signUpWithGoogle: "ساخت حساب از طریق گوگل",
    signIn: "وارد شوید",
    deleteCartItemParagraph: "از سبد خرید شما حذف شود؟",
    orderSummary: "خلاصه سفارش",
    orderInfo: "جزییات سفارش",
    deliveryFee: "هزینه ارسال",
    submitOrder: "ثبت سفارش",
    pay: "پرداخت",
    gotoCart: "برو به سبد خرید",
    viewCart: "مشاهده سبد خرید",
    count: "عدد",
    newest: "جدید ترین",
    oldest: "قدیمی ترین",
    cheapest: "ارزان ترین",
    mostExpensive: "گران ترین",
    bestSeller: "پرفروش ترین",
    filter: "فیلتر  ",
    emptyCart: "سبد خرید خالی است",
    shopNow: "خرید کن ببه",
    outOfStock: "ناموجود",
    outOfStockWarnMsg: "موجودی کالا در انبار کافی نیست.",
    deletedSuccessfully: "با موفقیت حذف شد.",
    updatedSuccessfully: "با موفقیت آپدیت شد.",
}